from pathlib import Path
import subprocess
root = Path(__file__).resolve().parents[1]
out = root/'build/gallery'; out.mkdir(parents=True, exist_ok=True)
source = (root/'main.swift').read_text().split('let app = NSApplication.shared')[0]
source += 'let app = NSApplication.shared\nlet week = AccountUsageWindow(remainingPercent: 73, usedPercent: 27, windowLabel: "1周", resetsAt: Date(timeIntervalSince1970: 1789344000), durationMinutes: 10080)\nlet short = AccountUsageWindow(remainingPercent: 42, usedPercent: 58, windowLabel: "5小时", resetsAt: Date(timeIntervalSince1970: 1789344000), durationMinutes: 300)\nlet balance = DeepSeekBalance(is_available: true, balance_infos: [.init(currency: "CNY", total_balance: "88.88", granted_balance: "0.00", topped_up_balance: "88.88"), .init(currency: "USD", total_balance: "0.00", granted_balance: "0.00", topped_up_balance: "0.00")])\nfor plus in [false, true] {\n    let usage = AccountUsage(shortWindow: plus ? short : nil, totalWindow: week, resetCredits: nil, planType: plus ? "plus" : "prolite", lastSuccessAt: Date(timeIntervalSince1970: 1789344000))\n    let snapshot = AppSnapshot(accountUsage: usage, threadUsage: UsageSnapshot(current: nil, recent: [], totalRecentTokens: 1234567, checkedAt: Date(timeIntervalSince1970: 1789344000), error: nil), checkedAt: Date(timeIntervalSince1970: 1789344000), nextRefreshAt: Date(timeIntervalSince1970: 1789344000), accountError: nil)\n    let view = QuotaDashboardView(snapshot: snapshot, balance: balance, error: nil, date: Date(timeIntervalSince1970: 1789344000))\n    let rep = view.bitmapImageRepForCachingDisplay(in: view.bounds)!\n    view.cacheDisplay(in: view.bounds, to: rep)\n    try! rep.representation(using: .png, properties: [:])!.write(to: URL(fileURLWithPath: "docs/assets/v0.11.0-" + (plus ? "plus" : "pro") + ".png"))\n}\n'
p = out/'main.swift'; p.write_text(source)
subprocess.run(['swift', str(p)],cwd=root,check=True)
print('Rendered native AppKit Pro/Plus panels with fictional data; not desktop screenshots')
